### ISSUE TITLE
Can’t connect to rtorrent

### ISSUE THREAD

**Issue by davida72** [romancin/rutorrent-flood-docker#48] opened 2019-01-13 01:07 UTC
I can get the flood dialog box that asks for the rtorrent port and server, but I don’t know what I should put there. Should it just work automatically? Is there a setting?

Thanks!

**Comment by davida72** [comment] 2019-01-13 20:33
I was able to get this working by changing my rtorrent.rc to read as follows.

```
# Prepare rtorrent communication socket
# execute.nothrow = rm,/run/php/.rtorrent.sock
# network.scgi.open_local = /run/php/.rtorrent.sock
# schedule = socket_chmod,0,0,"execute=chmod,0660,/run/php/.rtorrent.sock"
# schedule = socket_chgrp,0,0,"execute=chgrp,abc,/run/php/.rtorrent.sock"

scgi_port = 127.0.0.1:5000
```

I don't know if that change has any negative knock-on effects but so far, so good.

**Comment by themightykitten** [comment] 2019-01-25 22:40
It is Pyrocore that is preventing rtorrent from starting at all because of a bad config in rtorrent.rc
As a temporary fix, omment out everything regarding Pyrocore in the rtorrent.rc file

**Comment by chewlm86** [comment] 2019-01-29 23:52
Have the same problem with the Port and Server option.

But I was able to get it to connect using the Socket option with the following value,
`/run/php/.rtorrent.sock`

**Comment by romancin** [comment] 2019-02-28 05:53
Could you please test with the new images? Pyrocore install should have been fixed now. For me it’s working without changing anything in rtorrent.rc. Thank you.

**Comment by romancin** [comment] 2019-02-28 19:33
Closing. Confirmed it works on issue #46

**Closed by romancin** 2019-02-28 19:33 UTC
